// Developer Express Code Central Example:
// How to implement the Drag&Drop functionality for the CardView
// 
// We have created an example demonstrating how to implement the Drag&Drop
// functionality for the CardView.
// This functionality is encapsulated in the
// CardDragDropManager class. So, all you need to do is to attach this behavior to
// the GridControl.
// 
// You can find sample updates and versions for different programming languages here:
// http://www.devexpress.com/example=E4616

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardViewDragDrop.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
    }
}
